import { useState } from "react";
import StatusBadge from "../../components/StatusBadge.jsx";
import { AI_WORKSPACE_TEMPLATES } from "../../data/demo.js";

export default function AIWorkspace() {
  const [activeTemplate, setActiveTemplate] = useState(null);
  const [notes, setNotes] = useState("");
  const [generated, setGenerated] = useState(false);
  const [status, setStatus] = useState("draft");
  const [previewMode, setPreviewMode] = useState(false);

  const handleSelectTemplate = (tpl) => {
    setActiveTemplate(tpl);
    setNotes("");
    setGenerated(false);
    setStatus("draft");
    setPreviewMode(false);
  };

  const handleGenerate = () => setGenerated(true);
  const handleApprove = () => setStatus("awaiting approval");
  const handlePublish = () => setStatus("published");

  const placeholderDraft = activeTemplate
    ? `[Placeholder draft for "${activeTemplate.title}"]\n\nThis content would be generated by an AI provider based on your notes and team context. Connect an OpenAI-compatible provider in the admin settings to enable source-backed rewrites.\n\nUntil then, this is a placeholder you can manually edit before submitting for approval.`
    : "";

  return (
    <div className="flex flex-col gap-6 pb-8">
      <div className="hidden md:flex items-center justify-between mb-2">
        <h2 className="text-2xl font-semibold tracking-tight text-emerald-100" style={{ fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
          AI Coach Workspace
        </h2>
      </div>

      {/* Intro */}
      <div className="rounded-xl border p-5 bg-black border-emerald-800 flex flex-col gap-2">
        <p className="text-sm text-emerald-100 font-semibold">Prepare review-only drafts.</p>
        <p className="text-sm text-emerald-400">All content requires Preview → Edit → Approve → Publish. AI cannot publish, notify families, or create access rights.</p>
        <div className="mt-1 flex items-start gap-2 bg-yellow-950/40 border border-yellow-800 rounded-lg px-3 py-2">
          <iconify-icon icon="solar:warning-linear" width="16" class="text-yellow-400 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-yellow-300">OpenAI provider not configured — drafts use placeholder content. Connect a provider to enable source-backed rewrites.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Template grid */}
        <div className="flex flex-col gap-3">
          <p className="text-xs font-semibold text-emerald-500 uppercase tracking-wider px-1">Templates</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {AI_WORKSPACE_TEMPLATES.map(tpl => (
              <button
                key={tpl.id}
                onClick={() => handleSelectTemplate(tpl)}
                className={`w-full text-left rounded-xl border p-3 transition-colors min-h-[44px] flex items-start gap-3 ${
                  activeTemplate?.id === tpl.id
                    ? "bg-emerald-950/60 border-cyan-700"
                    : "bg-black border-emerald-800 hover:bg-emerald-950"
                }`}
              >
                <iconify-icon icon={tpl.icon} width="20" class="text-cyan-400 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-semibold text-emerald-100 leading-snug">{tpl.title}</p>
                  <p className="text-xs text-emerald-500 mt-0.5 leading-snug">{tpl.desc}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Work panel */}
        {activeTemplate ? (
          <div className="rounded-xl border p-5 bg-black border-emerald-800 flex flex-col gap-4">
            <div className="flex items-start justify-between gap-2 flex-wrap">
              <div>
                <p className="text-xs font-semibold text-emerald-500 uppercase tracking-wider mb-1">Work Panel</p>
                <p className="text-emerald-100 font-semibold">{activeTemplate.title}</p>
                <p className="text-xs text-emerald-500 mt-0.5">{activeTemplate.desc}</p>
              </div>
              <StatusBadge status={status} />
            </div>

            <div className="h-px w-full bg-emerald-900" />

            <div>
              <label className="text-xs text-emerald-400 mb-1 block font-medium">Context / Notes</label>
              <textarea
                rows={4}
                value={notes}
                onChange={e => setNotes(e.target.value)}
                placeholder="Paste your notes, key details, or context for the AI to use…"
                className="w-full bg-emerald-950/30 border border-emerald-800 rounded-lg px-3 py-2 text-emerald-100 text-sm focus:outline-none focus:border-cyan-600 resize-none"
              />
            </div>

            <button
              onClick={handleGenerate}
              className="px-4 py-2 rounded-lg bg-cyan-400 text-black text-sm font-semibold hover:bg-cyan-300 transition-colors min-h-[44px] w-fit"
            >
              Generate Draft
            </button>

            {generated && (
              <>
                <div className="h-px w-full bg-emerald-900" />

                <div className="flex items-center justify-between flex-wrap gap-2">
                  <p className="text-xs font-semibold text-emerald-500 uppercase tracking-wider">Draft Output</p>
                  <button onClick={() => setPreviewMode(v => !v)} className="text-cyan-400 hover:text-cyan-300 text-sm font-medium">
                    {previewMode ? "Edit" : "Preview"}
                  </button>
                </div>

                <textarea
                  rows={8}
                  defaultValue={placeholderDraft}
                  className="w-full bg-emerald-950/30 border border-emerald-800 rounded-lg px-3 py-2 text-emerald-100 text-sm focus:outline-none focus:border-cyan-600 resize-none font-mono"
                  readOnly={previewMode}
                />

                {previewMode && (
                  <div className="bg-emerald-950/20 border border-emerald-800 rounded-lg p-3">
                    <p className="text-xs font-semibold text-emerald-500 uppercase tracking-wider mb-2">Preview — How families will see this</p>
                    <p className="text-sm text-emerald-300 whitespace-pre-line leading-relaxed">{placeholderDraft}</p>
                  </div>
                )}

                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={handleApprove}
                    disabled={status !== "draft"}
                    className="px-4 py-2 rounded-lg border border-emerald-800 text-emerald-100 text-sm font-medium hover:bg-emerald-950 transition-colors min-h-[44px] disabled:opacity-40 disabled:cursor-not-allowed"
                  >
                    Submit for Approval
                  </button>
                  <button
                    onClick={handlePublish}
                    disabled={status !== "awaiting approval"}
                    className="px-4 py-2 rounded-lg bg-cyan-400 text-black text-sm font-semibold hover:bg-cyan-300 transition-colors min-h-[44px] disabled:opacity-40 disabled:cursor-not-allowed"
                  >
                    Publish
                  </button>
                </div>

                <div className="bg-red-950/30 border border-red-900 rounded-lg px-3 py-2 text-xs text-red-300 flex items-start gap-2">
                  <iconify-icon icon="solar:shield-check-linear" width="14" class="text-red-400 flex-shrink-0 mt-0.5" />
                  AI cannot publish, notify families, or create access rights. All drafts require human approval.
                </div>
              </>
            )}
          </div>
        ) : (
          <div className="rounded-xl border p-8 bg-black border-emerald-800 flex flex-col items-center justify-center gap-3 text-center">
            <iconify-icon icon="solar:document-text-linear" width="36" class="text-emerald-700" />
            <p className="text-emerald-500 text-sm">Select a template to get started</p>
          </div>
        )}
      </div>

      <p className="text-xs text-emerald-600 text-center mt-4">Demo data — changes are not persisted.</p>
    </div>
  );
}
